VIRTUES_CHOICES = (
    (1, 'Charity'),
    (2, 'Chastity'),
    (3, 'Diligence'),
    (4, 'Humility'),
    (5, 'Patience'),
    (6, 'Temperance'),
    (7, 'Kindness')
)
VIRTUE_CHARITY = VIRTUES_CHOICES[0][0]
VIRTUE_CHASTITY = VIRTUES_CHOICES[1][0]
VIRTUE_DILIGENCE = VIRTUES_CHOICES[2][0]
VIRTUE_HUMILITY = VIRTUES_CHOICES[3][0]
VIRTUE_PATIENCE = VIRTUES_CHOICES[4][0]
VIRTUE_TEMPERANCE = VIRTUES_CHOICES[5][0]
VIRTUE_KINDNESS = VIRTUES_CHOICES[6][0]
