# Generated by Django 3.0.7 on 2020-12-05 10:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Virtues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('virtue', models.CharField(choices=[(1, 'Charity'), (2, 'Chastity'), (3, 'Diligence'), (4, 'Humility'), (5, 'Patience'), (6, 'Temperance'), (7, 'Kindness')], default=1, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('action', models.TextField()),
                ('virtue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtues.Virtues')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
