# Generated by Django 3.0.7 on 2020-12-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtues', '0002_auto_20201205_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtues',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
