# Generated by Django 3.0.7 on 2020-12-05 10:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('virtues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtues.Actions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
